"""
Application name to package name mapping module.

Mapping is loaded from YAML files in real-time:
1. default_package_map.yaml - Default mappings for common applications
2. user_package_map.yaml - User-defined mappings (highest priority)

Changes to YAML files take effect immediately without restart.
"""

import os
import difflib
from typing import Dict, List, Optional

# Project root directory
_PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
_DEFAULT_MAP_FILE = os.path.join(_PROJECT_ROOT, "config", "default_package_map.yaml")
_USER_MAP_FILE = os.path.join(_PROJECT_ROOT, "config", "user_package_map.yaml")


def _load_yaml_map(file_path: str) -> Dict[str, str]:
    """Load mapping from YAML file."""
    if not os.path.exists(file_path):
        return {}
    
    try:
        import yaml
        with open(file_path, "r", encoding="utf-8") as f:
            data = yaml.safe_load(f)
            return data if isinstance(data, dict) else {}
    except ImportError:
        # No yaml library, use simple parsing
        mapping = {}
        try:
            with open(file_path, "r", encoding="utf-8") as f:
                for line in f:
                    line = line.strip()
                    if line and not line.startswith("#") and ":" in line:
                        parts = line.split(":", 1)
                        if len(parts) == 2:
                            key = parts[0].strip().strip('"').strip("'")
                            value = parts[1].strip().strip('"').strip("'")
                            if key and value:
                                mapping[key] = value
            return mapping
        except Exception:
            return {}
    except Exception:
        return {}


def get_package_name_map() -> Dict[str, str]:
    """
    Get merged mapping table (reloaded on each call).
    
    Load order: default mapping -> user mapping (override)
    Changes to YAML files take effect immediately.
    
    Returns:
        Merged {app_name: package_name} mapping dictionary
    """
    merged_map = _load_yaml_map(_DEFAULT_MAP_FILE)
    user_map = _load_yaml_map(_USER_MAP_FILE)
    merged_map.update(user_map)
    return merged_map


# For backward compatibility
package_name_map = get_package_name_map()


def reload_package_name_map() -> None:
    """Refresh global mapping table."""
    global package_name_map
    package_name_map = get_package_name_map()


def find_package_name(app_name: str) -> str:
    """
    Find package name by app name (real-time YAML reading).
    
    Search order:
    1. Exact match (case-sensitive)
    2. Lowercase match
    3. Fuzzy match
    
    Args:
        app_name: Application name
        
    Returns:
        Package name
        
    Raises:
        AssertionError: No matching package name found
    """
    current_map = get_package_name_map()
    app_name_lowered = app_name.lower()
    
    # 1. Exact match
    if app_name in current_map:
        return current_map[app_name]
    
    # 2. Lowercase match
    map_lowered = {k.lower(): v for k, v in current_map.items()}
    if app_name_lowered in map_lowered:
        return map_lowered[app_name_lowered]
    
    # 3. Fuzzy match
    max_match = {"name": None, "score": 0}
    
    for key in current_map.keys():
        score = difflib.SequenceMatcher(None, app_name_lowered, key.lower()).ratio()
        if score > max_match["score"]:
            max_match["name"] = key
            max_match["score"] = score
    
    assert max_match["name"] is not None, f"Cannot find package name for app {app_name}"
    return current_map[max_match["name"]]


def get_list_of_package_names() -> List[Dict[str, str]]:
    """
    Get list of all app mappings (real-time).
    
    Returns:
        List of {app_name, package_name} dictionaries
    """
    current_map = get_package_name_map()
    return [
        {"app_name": app_name, "package_name": package_name}
        for app_name, package_name in current_map.items()
    ]


def load_package_map() -> Dict[str, str]:
    """Alias for get_package_name_map for compatibility."""
    return get_package_name_map()


def save_user_package_map(mapping: Dict[str, str]) -> bool:
    """
    Save user-defined mapping.
    
    Args:
        mapping: App name to package name mapping dictionary
        
    Returns:
        Whether save was successful
    """
    try:
        import yaml
        os.makedirs(os.path.dirname(_USER_MAP_FILE), exist_ok=True)
        with open(_USER_MAP_FILE, "w", encoding="utf-8") as f:
            f.write("# User-defined app name to package name mapping\n")
            f.write("# This file is auto-generated by scan function and can be manually edited\n")
            f.write("# Priority is higher than default_package_map.yaml\n\n")
            yaml.dump(mapping, f, allow_unicode=True, sort_keys=False, default_flow_style=False)
        return True
    except ImportError:
        try:
            os.makedirs(os.path.dirname(_USER_MAP_FILE), exist_ok=True)
            with open(_USER_MAP_FILE, "w", encoding="utf-8") as f:
                f.write("# User-defined app name to package name mapping\n")
                f.write("# This file is auto-generated by scan function and can be manually edited\n\n")
                for app_name, pkg_name in mapping.items():
                    if ":" in app_name or "#" in app_name:
                        f.write(f'"{app_name}": {pkg_name}\n')
                    else:
                        f.write(f"{app_name}: {pkg_name}\n")
            return True
        except Exception as e:
            print(f"[ERROR] Failed to save user_package_map.yaml: {e}")
            return False
    except Exception as e:
        print(f"[ERROR] Failed to save user_package_map.yaml: {e}")
        return False
